#!/usr/bin/env julia --project

using ArgParse, OSMTool

s = ArgParseSettings()

@add_arg_table! s begin
    "--filter-ways"
        help = "Filter ways based on tags"
        arg_type = String
    "--filter-nodes"
        help = "Filter nodes based on tags"
        arg_type = String
    "--no-relations"
        help = "Don't parse relations"
    "--write-gdal-ways"
        help = "Write ways to a GDAL file"
        arg_type = String
    "--write-gdal-nodes"
        help = "Write nodes to a GDAL file"
        arg_type = String
    "--gdal-driver"
        help = "GDAL driver to use (default 'ESRI Shapefile')"
        default = "ESRI Shapefile"
    "--gdal-tags"
        help = "Tags to retain in GDAL output, comma-separated"
        arg_type = String
        default = "highway,name"
    "--split-ways-at-intersections"
        help = "Break ways at intersection nodes (i.e. create noded network)"
        action = :store_true
    "--speed-table"
        help = "CSV with highway and speed columns specifying assumed max speeds when not specified"
        arg_type = String
    "input_file"
        help = "Input file, OSM PBF format"
end

OSMTool.main(parse_args(s))